### ISSUE TITLE
Chapter 2 subsec colorbars example data missing

### ISSUE THREAD

**Issue by Nafalem231** [matplotlib/AnatomyOfMatplotlib#26]
Seems like the example data used in chapter 2 at the colorbar example is no longer supported as of py 3.1. bivariate_normal.npy is not in any folder and has apparantly been discontinued.

**Comment by ggodreau** [comment]
@Nafalem231 FYI :point_up:

**Comment by WeatherGod** [comment]
The conda-forge distribution of matplotlib has the sample-data in a separate package in order to reduce the size of the download (since most users probably wouldn't need it). The data itself hasn't been discontinued in the main repo, which is why I never noticed this problem until this year's SciPy conference.
